/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;
import databases.koneksi; 
import java.sql.PreparedStatement; 
import javax.swing.JOptionPane; 
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;

/**
 *
 * @author ASUS
 */
public class frameKeluarga extends javax.swing.JFrame {
     public koneksi objekku;
    public DefaultTableModel modelku;

    /**
     * Creates new form frameKeluarga
     */
    public frameKeluarga() {
         initComponents();
        this.setLocationRelativeTo(null); 
        objekku = new koneksi(); 
        modelku = new DefaultTableModel();
        jTablekeluarga.setModel(modelku);
        modelku.addColumn("No KK");
        modelku.addColumn("Berlaku");
        modelku.addColumn("Alamat");
        modelku.addColumn("RT");
        modelku.addColumn("Kelurahan");
        modelku.addColumn("Kode Pos");
        
          loadtablekeluarga();
    }
    
    public void loadtablekeluarga(){
          try{
             modelku.getDataVector().removeAllElements();
             modelku.fireTableDataChanged();
        
        String sql ="select * from data_keluarga order by NoKK asc";
        PreparedStatement query = objekku.konek.prepareStatement(sql);
        ResultSet datanya = query.executeQuery();
        while (datanya.next()){
            Object[] baris = new Object[6];
            baris[0]= datanya.getString("NoKK");
            baris[1]= datanya.getString("Berlaku_sampai");
            baris[2]= datanya.getString("Alamat");
            baris[3]= datanya.getString("RT");
            baris[4]= datanya.getString("Kelurahan");
            baris[5]= datanya.getString("Kode_pos");
            
             modelku.addRow(baris); 
        }
        datanya.close();
        query.close();
    }catch (Exception e) {
         JOptionPane.showMessageDialog(this, e.toString());
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtkk = new javax.swing.JTextField();
        txtberl = new javax.swing.JTextField();
        txtalmt = new javax.swing.JTextField();
        txtrt = new javax.swing.JTextField();
        txtklh = new javax.swing.JTextField();
        txtpos = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btnhps = new javax.swing.JButton();
        btnedt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablekeluarga = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        btnrpt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("No KK");

        jLabel2.setText("Berlaku");

        jLabel3.setText("Alamat");

        jLabel4.setText("RT");

        jLabel5.setText("Kelurahan");

        jLabel6.setText("Kode Pos");

        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnhps.setText("HAPUS");
        btnhps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhpsActionPerformed(evt);
            }
        });

        btnedt.setText("EDIT");
        btnedt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnedtActionPerformed(evt);
            }
        });

        jTablekeluarga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablekeluarga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablekeluargaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablekeluarga);

        jLabel7.setText("Cari");

        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcariKeyPressed(evt);
            }
        });

        btnrpt.setText("Report");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnsimpan)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                    .addComponent(btnhps)
                                    .addGap(35, 35, 35)
                                    .addComponent(btnedt))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(15, 15, 15))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))))
                                    .addGap(75, 75, 75)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtkk)
                                        .addComponent(txtberl)
                                        .addComponent(txtalmt)
                                        .addComponent(txtrt)
                                        .addComponent(txtklh)
                                        .addComponent(txtpos, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(btnrpt)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtkk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtberl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtalmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtklh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addComponent(jLabel6))
                            .addComponent(txtpos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsimpan)
                            .addComponent(btnhps)
                            .addComponent(btnedt))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnrpt)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
         try {
            if(txtkk.getText().isEmpty()){             
                JOptionPane.showMessageDialog(this, "No KK Belum di Isi");
                txtkk.requestFocus();
                
            }else if(txtberl.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Berlaku Belum di Isi");
                txtberl.requestFocus();
                
            }else if(txtalmt.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Alamat Belum di Isi");
                txtalmt.requestFocus();
                   
            }else if(txtrt.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "RT Belum di Isi");
                txtrt.requestFocus();
            }else if(txtklh.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Kelurahan Belum di Isi");
                txtklh.requestFocus();
                }else if(txtpos.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Kode Pos Belum di Isi");
                txtpos.requestFocus();
                }else{
                    
                String sqlsimpan = "insert into data_keluarga (NoKK,Berlaku_sampai,Alamat,RT,Kelurahan,Kode_pos) value(?,?,?,?,?,?)";
                PreparedStatement simpan = objekku.konek.prepareStatement(sqlsimpan);
                simpan.setString(1, txtkk.getText());
                simpan.setString(2, txtberl.getText());
                simpan.setString(3, txtalmt.getText());
                simpan.setString(4, txtrt.getText());
                 simpan.setString(5, txtklh.getText());
                  simpan.setString(6, txtpos.getText());                 
                   simpan.executeUpdate();
                   loadtablekeluarga();
                JOptionPane.showMessageDialog(this, "Data Berhasil di Simpan");
            }
                  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }           
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnedtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnedtActionPerformed
        // TODO add your handling code here:
          try {
            String sql = "update data_keluarga set Alamat = ?, Kelurahan = ? where NoKK = ?";
            PreparedStatement ubah = objekku.konek.prepareStatement(sql);
            ubah.setString(1, txtalmt.getText());
           
            ubah.setString(2, txtklh.getText());
            
            ubah.setString(3, txtkk.getText());
            
            ubah.executeUpdate();
            loadtablekeluarga();
            JOptionPane.showMessageDialog(this, "Data Berhasil di Ubah");
            
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_btnedtActionPerformed

    private void jTablekeluargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablekeluargaMouseClicked
        // TODO add your handling code here:
        int i= jTablekeluarga.getSelectedRow();
        String NoKK = jTablekeluarga.getValueAt(i, 0).toString();
        String Berlaku_sampai = jTablekeluarga.getValueAt(i, 1).toString();
        String Alamat = jTablekeluarga.getValueAt(i, 2).toString();
        String RT = jTablekeluarga.getValueAt(i, 3).toString();
        String Kelurahan = jTablekeluarga.getValueAt(i, 4).toString();
         String Kode_pos = jTablekeluarga.getValueAt(i, 5).toString();
          
         txtkk.setText(NoKK);
        txtberl.setText(Berlaku_sampai);
        txtalmt.setText(Alamat);
        txtrt.setText(RT);
        txtklh.setText(Kelurahan);
        txtpos.setText(Kode_pos);
    }//GEN-LAST:event_jTablekeluargaMouseClicked

    private void btnhpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhpsActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "delete from data_keluarga where NoKK=?";
            PreparedStatement hapus = objekku.konek.prepareStatement(sql);
            hapus.setString(1, txtkk.getText());
            hapus.executeUpdate();
            
          loadtablekeluarga();
            JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
            
            txtkk.setText(null);
            txtberl.setText(null);
            txtalmt.setText(null);
            txtrt.setText(null);
            txtklh.setText(null);
            txtpos.setText(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    
    }//GEN-LAST:event_btnhpsActionPerformed

    private void txtcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyPressed
        // TODO add your handling code here:
        try {
           modelku.getDataVector().removeAllElements();
           modelku.fireTableDataChanged();
           
           String sqlcari = "select * from data_keluarga where npm like '%"+txtcari.getText()+"%' or"
                + "Alamat like '%"+txtcari.getText()+"%' or RT like '%"+txtcari.getText()+"%'";
           ResultSet cari = objekku.konek.createStatement().executeQuery(sqlcari);
           
           while(cari.next()) {
                Object[] baris = new Object[3];
                baris[0] = cari.getString("NoKK");
                baris[1] = cari.getString("Alamat");
                baris[2] = cari.getString("RT");
                modelku.addRow(baris);
            }
        } catch (Exception e){
            
        }
    
    }//GEN-LAST:event_txtcariKeyPressed

     private void SIMPANActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        try {
            if(txtkk.getText().isEmpty()){             
                JOptionPane.showMessageDialog(this, "No KK Belum di Isi");
                txtkk.requestFocus();
                
            }else if(txtberl.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Berlaku Belum di Isi");
                txtberl.requestFocus();
                
            }else if(txtalmt.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Alamat Belum di Isi");
                txtalmt.requestFocus();
                   
            }else if(txtrt.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "RT Belum di Isi");
                txtrt.requestFocus();
            }else if(txtklh.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Kelurahan Belum di Isi");
                txtklh.requestFocus();
                }else if(txtpos.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Kode Pos Belum di Isi");
                txtpos.requestFocus();
                }else{
                    
                String sqlsimpan = "insert into data_keluarga (NoKK,Berlaku_sampai,Alamat,RT,Kelurahan,Kode_pos) value(?,?,?)";
                PreparedStatement simpan = objekku.konek.prepareStatement(sqlsimpan);
                simpan.setString(1, txtkk.getText());
                simpan.setString(2, txtberl.getText());
                simpan.setString(3, txtalmt.getText());
                simpan.setString(4, txtrt.getText());
                 simpan.setString(5, txtklh.getText());
                  simpan.setString(6, txtpos.getText());                 
                   simpan.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Data Berhasil di Simpan");
            }
                  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
     }
     
     private void HAPUSActionPerformed(java.awt.event.ActionEvent evt) { 
            // TODO add your handling code here:
     }
     private void UBAHActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
       try {
            String sql = "update data_keluarga set Alamat = ?, Kelurahan = ? where NoKK = ?";
            PreparedStatement ubah = objekku.konek.prepareStatement(sql);
            ubah.setString(1, txtalmt.getText());
            ubah.setString(2, txtklh.getText());
            ubah.setString(3, txtkk.getText());
            ubah.executeUpdate();
             loadtablekeluarga();
            JOptionPane.showMessageDialog(this, "Data Berhasil di Ubah");
            
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameKeluarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameKeluarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameKeluarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameKeluarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameKeluarga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnedt;
    private javax.swing.JButton btnhps;
    private javax.swing.JButton btnrpt;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablekeluarga;
    private javax.swing.JTextField txtalmt;
    private javax.swing.JTextField txtberl;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtkk;
    private javax.swing.JTextField txtklh;
    private javax.swing.JTextField txtpos;
    private javax.swing.JTextField txtrt;
    // End of variables declaration//GEN-END:variables
}
